### ISSUE TITLE
Range down and up problem

### ISSUE THREAD

**Issue by huseyin-yildiz** [hariangr/HsvRangeTool#1]
when low is greater than, it can not mask.For example, i can not use it for red color. Like shown in the picture.  
![Adsız](https://user-images.githubusercontent.com/76514563/189318629-23f7f373-5efa-4525-9894-92efed3da32f.png)

**Comment by hariangr** [comment]
The easiest solution would be to create two different mask, one using the left side of the red spectrum (0-idk 80), and the second mask using the right side (220-255)

Then add the two mask together to create a complete red spectrum boolean mask
